# Generated by Django 3.2.8 on 2021-11-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_segurosencabezado'),
    ]

    operations = [
        migrations.AddField(
            model_name='segurosencabezado',
            name='subtitulo',
            field=models.CharField(default='ded', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segurosencabezado',
            name='titulo',
            field=models.CharField(default='dsd', max_length=250),
            preserve_default=False,
        ),
    ]
