# Generated by Django 3.2.8 on 2021-11-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20211103_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.ImageField(upload_to='images')),
                ('titulo', models.CharField(max_length=250)),
                ('contenido', models.CharField(max_length=1500)),
            ],
        ),
    ]
