# Generated by Django 3.2.8 on 2021-11-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_seguro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguro',
            name='contenido',
            field=models.TextField(),
        ),
    ]
