# Generated by Django 3.2.8 on 2021-11-07 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_alter_seguro_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguro',
            name='posicion',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
