# Generated by Django 3.2.8 on 2021-11-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_seguro_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quienessomos',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
    ]
