# Generated by Django 3.2.8 on 2021-11-08 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20211107_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Home'},
        ),
        migrations.AlterModelOptions(
            name='quienessomos',
            options={'verbose_name': 'Quienes Somos', 'verbose_name_plural': 'Quienes Somos'},
        ),
        migrations.AlterModelOptions(
            name='segurosencabezado',
            options={'verbose_name': 'Seguros Encabezado', 'verbose_name_plural': 'Seguros Encabezado'},
        ),
    ]
